### ISSUE TITLE
Implicict return with arrow functions

### ISSUE THREAD

**Issue by danielo515** [cjihrig/hapi-scope-start#7]
Hello,

I like the readability this rule adds to functions with big body, however it does not plays well with arrow functions with implicit return.
Is there any way to configure it ? Le me explain with examples:

```javascript
const myFn = () => {  // i do like this
   
  code
}

// The linter will complain here:

(x) => x.map( 
                       y => y.someProp
               )

// I am forced to write this instead

(x) => 

    x.map( 
                       y => y.someProp
               )
```

Please note that the example I provided is simplistic. This is a common patter for me for example while using promises:

```javascript
(x) => new Promise((resolve,reject) => {
    // some code here
}
```

Regards

**Comment by cjihrig** [comment]
This rule is part of the hapi ecosystem linting setup. I don't think the [hapi style guide](https://hapijs.com/styleguide) allows for what you're asking for, and I personally don't like implicit returns.

I'm going to close this issue, but if you want to submit a patch that adds support, I'll take a look.
